# Generated by Django 3.0.2 on 2020-02-08 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='course',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='register',
            name='sem',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
