# Generated by Django 3.0.2 on 2020-02-08 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20200208_1908'),
    ]

    operations = [
        migrations.DeleteModel(
            name='register',
        ),
    ]
